/**
 * tokens.mjs → tokens.css
 *
 * Same discipline as scripts/build-requirements.mjs: the generator is
 * exhaustive and refuses to guess. A semantic role that points at a primitive
 * which does not exist stops the build; it does not default to black.
 *
 *   node scripts/build.mjs            write tokens.css
 *   node scripts/build.mjs --verify   exit 1 if tokens.css is stale
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  breakpoint,
  hexToChannels,
  measure,
  motion,
  primitives,
  radius,
  semantic,
  shadow,
  type,
} from "../tokens.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, "../tokens.css");

export function render() {
  const lines = [];
  const push = (s = "") => lines.push(s);

  push("/*");
  push(" * GENERATED by packages/brand/scripts/build.mjs from tokens.mjs. Do not edit.");
  push(" *");
  push(" * Change a value in tokens.mjs, then `npm run build -w @hm/brand`.");
  push(" * `npm run verify -w @hm/brand` fails when this file is stale.");
  push(" *");
  push(" * Naming:");
  push(" *   --sm-<primitive>          raw value          --sm-red-500");
  push(" *   --sm-<primitive>-rgb      channels, for rgb(var(--x) / a)");
  push(" *   --sm-color-<role>         semantic color    --sm-color-accent → var(--sm-red-500)");
  push(
    " *   --sm-font-<role>          semantic face      --sm-font-display → var(--sm-face-serif)",
  );
  push(" */");
  push(":root {");

  push("  /* primitives · color */");
  for (const [name, hex] of Object.entries(primitives.color)) {
    if (!/^#[0-9A-F]{6}$/i.test(hex)) {
      throw new Error(`primitive ${name} is not a hex color: ${hex}`);
    }
    // Lowercased on the way out purely so the generated file is Prettier-clean
    // and `npm run format` cannot make it disagree with the generator.
    push(`  --sm-${name}: ${hex.toLowerCase()};`);
    push(`  --sm-${name}-rgb: ${hexToChannels(hex)};`);
  }

  push("");
  push("  /* primitives · faces */");
  for (const [name, stack] of Object.entries(primitives.face)) {
    push(`  --sm-face-${name}: ${stack};`);
  }

  push("");
  push("  /* semantic · color (roles point at primitives; components use only these) */");
  for (const [role, primitive] of Object.entries(semantic.color)) {
    if (!(primitive in primitives.color)) {
      throw new Error(`color role "${role}" points at unknown primitive "${primitive}"`);
    }
    push(`  --sm-color-${role}: var(--sm-${primitive});`);
    push(`  --sm-color-${role}-rgb: var(--sm-${primitive}-rgb);`);
  }

  push("");
  push("  /* semantic · type */");
  for (const [role, face] of Object.entries(semantic.font)) {
    if (!(face in primitives.face))
      throw new Error(`font role "${role}" points at unknown face "${face}"`);
    push(`  --sm-font-${role}: var(--sm-face-${face});`);
  }
  for (const [step, t] of Object.entries(type.size)) {
    push(`  --sm-text-${step}: ${t.size};`);
    push(`  --sm-leading-${step}: ${t.line};`);
  }
  for (const [name, v] of Object.entries(type.tracking)) push(`  --sm-tracking-${name}: ${v};`);
  for (const [name, v] of Object.entries(type.weight)) push(`  --sm-weight-${name}: ${v};`);

  push("");
  push("  /* radius */");
  for (const [name, v] of Object.entries(radius)) push(`  --sm-radius-${name}: ${v};`);

  push("");
  push("  /* shadow */");
  for (const [name, v] of Object.entries(shadow)) push(`  --sm-shadow-${name}: ${v};`);

  push("");
  push("  /* motion */");
  for (const [name, v] of Object.entries(motion.ease)) push(`  --sm-ease-${name}: ${v};`);
  for (const [name, v] of Object.entries(motion.duration)) push(`  --sm-duration-${name}: ${v};`);

  push("");
  push("  /* measure */");
  for (const [name, v] of Object.entries(measure)) push(`  --sm-measure-${name}: ${v};`);

  push("");
  push("  /* breakpoint (informational; media queries cannot read custom properties) */");
  for (const [name, v] of Object.entries(breakpoint)) push(`  --sm-breakpoint-${name}: ${v};`);

  push("}");
  push("");
  return lines.join("\n");
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const css = render();
  if (process.argv.includes("--verify")) {
    let current = "";
    try {
      current = readFileSync(OUT, "utf8");
    } catch {
      /* missing counts as stale */
    }
    if (current !== css) {
      console.error(
        "packages/brand/tokens.css is out of date with tokens.mjs.\n" +
          "Run `npm run build -w @hm/brand` and commit the result.",
      );
      process.exit(1);
    }
    console.log("brand tokens: tokens.css matches tokens.mjs");
  } else {
    writeFileSync(OUT, css);
    console.log(`wrote ${OUT}`);
  }
}
