/**
 * The DU submission tables, derived from Fannie Mae's specification.
 *
 * Everything here is generated by `scripts/build-du.mjs` and committed, for the
 * reason `packages/requirements/src/generated.ts` is: a build step that has to
 * run before TypeScript can resolve a type is a build step that breaks
 * somebody's editor. `npm run du:verify` regenerates in memory and fails on
 * drift, so the committed copies cannot silently diverge from the spec.
 *
 * Everything the generator reads is vendored, in `packages/du-schema` — the
 * MISMO schema chain, Fannie's eighteen shipped samples, and Fannie's
 * specification workbook. So `du:verify` rebuilds all six tables and fails on
 * any difference on a machine that has this repository and nothing else: there
 * is no environment to set, no corpus to obtain, and no half of the check that
 * skips.
 *
 * Nothing here is wired to a route or a screen. `emitSubmission` below is the
 * first thing in this repository that produces a DU submission, and nothing in
 * the product calls it: no route assembles one and nothing transports one.
 * `identity.ts` and the writers are how a DU row and its owner arcs reach
 * Postgres at all, because the database refuses a row that has no owner and
 * only a transaction carrying both can satisfy it.
 *
 * The pipeline is assemble -> preflight -> emit, and the middle step refuses:
 * `emitSubmission` returns bytes or it throws, and there is no argument that
 * turns the gate off. `preflightSubmission` is the same run without the bytes,
 * for a caller that wants to know what is missing before it asks for them.
 *
 * **The serializer is not exported, and that is what makes the sentence above
 * true of the module and not only of one function in it.** A caller holding
 * both `assembleSubmission` and a serializer can compose them and get bytes no
 * check ever saw, which makes the gate a report. So `emitDocument` stays
 * inside: the only way out of here with bytes is through the refusal. A test
 * that needs ungated bytes imports `./emit.js` by path, which nothing outside
 * this package can do.
 */

import { emitDocument } from "./emit.js";
import { assembleSubmission, type AssembleOptions, type DuReader } from "./assemble/index.js";
import { loadIdentityKeys } from "./assemble/load.js";
import { DuPreflightRefusal, runPreflight, type DuPreflightReport } from "./preflight/index.js";

/**
 * One application, as the bytes a DU submission is, or a refusal.
 *
 * The assembled document is **never persisted, never logged and never
 * snapshotted**. It is the one place in this system where up to four cleartext
 * taxpayer identifiers exist at once, and the obvious wrong thing to build
 * beside it is an append-only "what we submitted" archive: it would wear this
 * repository's own append-only pattern and be a plaintext SSN store. Whether a
 * submitted document is retained at all is a privacy question with an owner,
 * and nothing here answers it by choosing a table.
 *
 * A casefile the preflight finds fault with raises `DuPreflightRefusal` and
 * produces no bytes. The findings carry XPaths and row ids and no values, so
 * the exception is safe to log — which the document itself would not be.
 */
export async function emitSubmission(
  db: DuReader,
  applicationId: string,
  options: AssembleOptions,
): Promise<string> {
  const document = await assembleSubmission(db, applicationId, options);
  const report = runPreflight({
    document,
    identities: await loadIdentityKeys(db, applicationId),
  });
  if (!report.ok) throw new DuPreflightRefusal(report.findings);
  return emitDocument(document);
}

/**
 * What the gate would say, without asking for the bytes.
 *
 * The same run as the one inside `emitSubmission`: a caller that wants to know
 * whether a casefile is emittable gets the answer from the same predicates that
 * would refuse it, rather than from a second list that could drift.
 */
export async function preflightSubmission(
  db: DuReader,
  applicationId: string,
  options: AssembleOptions,
): Promise<DuPreflightReport> {
  return runPreflight({
    document: await assembleSubmission(db, applicationId, options),
    identities: await loadIdentityKeys(db, applicationId),
  });
}

export { CHILD_ORDER, TYPE_FOR_PATH } from "./generated/order.js";
export {
  DU_ASSET_TYPES_BY_SECTION,
  DU_ENUMERATIONS,
  LOCAL_ENUMERATIONS,
} from "./generated/enums.js";
export {
  DU_ARCROLES,
  DU_RELATIONSHIP_XPATH,
  type DuArcRole,
  type DuArcRoleEndpoint,
} from "./generated/arcroles.js";
export { DU_FORMATS, type DuFormat } from "./generated/lengths.js";
export {
  DU_CARDINALITY,
  type DuCardinality,
  type DuContainerCardinality,
} from "./generated/cardinality.js";
export {
  DU_CONDITIONALITY,
  DU_CONDITION_STATEMENTS,
  type DuCondition,
  type DuConditionalityEntry,
  type DuRequirement,
} from "./generated/conditionality.js";
export {
  assetIdentityKeys,
  liabilityIdentityKeys,
  resolveIdentities,
  UNMATCHED_PREFIX,
  type AddressFacts,
  type AmbiguousGroup,
  type AssetIdentityFacts,
  type IdentityKeys,
  type IdentityPlan,
  type LiabilityIdentityFacts,
  type ResolvedIdentity,
  type VendorItem,
} from "./identity.js";
export {
  writeAsset,
  writeExpense,
  writeLiability,
  type MatchOnIdentity,
  type DuOwner,
  type DuSupersede,
  type DuTransaction,
  type NonEmpty,
  type WriteAssetInput,
  type WriteExpenseInput,
  type WriteLiabilityInput,
} from "./writer.js";

export {
  CONDITIONAL_RULES,
  DuPreflightRefusal,
  DU_SUBSET_AT,
  NOT_CHECKED_AGAINST_A_SUBSET,
  REQUIRED_RULES,
  runPreflight,
  type DuIdentityRow,
  type DuPreflightCheck,
  type DuPreflightFinding,
  type DuPreflightInput,
  type DuPreflightReport,
} from "./preflight/index.js";

export { assembleSubmission, type AssembleOptions, type DuReader } from "./assemble/index.js";
export {
  assertInstitutionEmittable,
  placeholdersIn,
  LENDER_LOAN_IDENTIFIER_FORMAT,
  PLACEHOLDER_INSTITUTION,
  SUBMITTING_PARTY_IDENTIFIER_FORMAT,
  type DuInstitution,
} from "./institution.js";
export {
  assertDealPartiesEmittable,
  assertOriginatorEmittable,
  originatorPlaceholdersIn,
  PLACEHOLDER_ORIGINATOR,
  COMPANY_NAME_FORMAT,
  COMPANY_NMLS_FORMAT,
  ORIGINATOR_FIRST_NAME_FORMAT,
  ORIGINATOR_LAST_NAME_FORMAT,
  ORIGINATOR_NMLS_FORMAT,
  widthOf,
  type DuOriginator,
} from "./originator.js";
export type { TaxpayerIdentifierResolver } from "./assemble/parties.js";
export {
  attributesOnly,
  compact,
  container,
  leaf,
  type DuNode,
  type MaybeNode,
} from "./document.js";
export {
  assertNCName,
  createLabelIndex,
  createLabels,
  employerKey,
  type DuLabelIndex,
  type DuLabelKind,
  type DuLabels,
} from "./labels.js";
export {
  renderAmount,
  renderCount,
  renderDate,
  renderDateTime,
  renderIndicator,
  renderPercent,
} from "./values.js";
