/**
 * The DU submission tables, derived from Fannie Mae's specification.
 *
 * Everything here is generated by `scripts/build-du.mjs` and committed, for the
 * reason `packages/requirements/src/generated.ts` is: a build step that has to
 * run before TypeScript can resolve a type is a build step that breaks
 * somebody's editor. `npm run du:verify` regenerates in memory and fails on
 * drift, so the committed copies cannot silently diverge from the spec.
 *
 * The MISMO schema chain the generator reads is vendored, in
 * `packages/du-schema/xsd` — which is what lets `du:verify` re-derive every
 * child sequence in `generated/order.ts` on a machine that has nothing else,
 * and re-count from the eighteen vendored samples which arcs in
 * `generated/arcroles.ts` a shipped DU document actually carries. Fannie Mae's
 * workbook is not: the generator reads it from DU_SPEC_DIR and names what it
 * could not check when that is unset.
 *
 * Nothing here is wired to a route or a screen. The generated tables are what
 * the serializer will emit against, and the serializer comes later; the writers
 * below are how a DU row and its owner arcs reach Postgres at all, because the
 * database refuses a row that has no owner and only a transaction carrying both
 * can satisfy it. `identity.ts` is what lets a second pull recognize a row it
 * already wrote rather than inserting a twin beside it.
 */

export { CHILD_ORDER, TYPE_FOR_PATH } from "./generated/order.js";
export {
  DU_ASSET_TYPES_BY_SECTION,
  DU_ENUMERATIONS,
  LOCAL_ENUMERATIONS,
} from "./generated/enums.js";
export {
  DU_ARCROLES,
  DU_RELATIONSHIP_XPATH,
  type DuArcRole,
  type DuArcRoleEndpoint,
} from "./generated/arcroles.js";
export { DU_FORMATS, type DuFormat } from "./generated/lengths.js";
export {
  DU_CARDINALITY,
  type DuCardinality,
  type DuContainerCardinality,
} from "./generated/cardinality.js";
export {
  DU_CONDITIONALITY,
  DU_CONDITION_STATEMENTS,
  type DuCondition,
  type DuConditionalityEntry,
  type DuRequirement,
} from "./generated/conditionality.js";
export {
  assetIdentityKeys,
  liabilityIdentityKeys,
  resolveIdentities,
  UNMATCHED_PREFIX,
  type AddressFacts,
  type AmbiguousGroup,
  type AssetIdentityFacts,
  type IdentityKeys,
  type IdentityPlan,
  type LiabilityIdentityFacts,
  type ResolvedIdentity,
  type VendorItem,
} from "./identity.js";
export {
  writeAsset,
  writeExpense,
  writeLiability,
  type MatchOnIdentity,
  type DuOwner,
  type DuSupersede,
  type DuTransaction,
  type NonEmpty,
  type WriteAssetInput,
  type WriteExpenseInput,
  type WriteLiabilityInput,
} from "./writer.js";
