/**
 * The XPaths the checks name, spelled once.
 *
 * Every generated table is keyed on the full path from `MESSAGE` down, so a
 * check that names a container has to spell the whole thing; writing
 * `${DEAL}/ASSETS/ASSET` in eleven files is eleven chances to typo a key that
 * then looks up nothing and passes.
 */

export const MESSAGE = "MESSAGE";
export const ABOUT_VERSION = `${MESSAGE}/ABOUT_VERSIONS/ABOUT_VERSION`;
export const DEAL = `${MESSAGE}/DEAL_SETS/DEAL_SET/DEALS/DEAL`;

export const ASSET = `${DEAL}/ASSETS/ASSET`;
export const ASSET_DETAIL = `${ASSET}/ASSET_DETAIL`;
export const OWNED_PROPERTY = `${ASSET}/OWNED_PROPERTY`;
export const OWNED_PROPERTY_DETAIL = `${OWNED_PROPERTY}/OWNED_PROPERTY_DETAIL`;

export const COLLATERAL = `${DEAL}/COLLATERALS/COLLATERAL`;
export const SUBJECT_PROPERTY = `${COLLATERAL}/SUBJECT_PROPERTY`;
export const SUBJECT_PROPERTY_ADDRESS = `${SUBJECT_PROPERTY}/ADDRESS`;
export const SUBJECT_PROPERTY_DETAIL = `${SUBJECT_PROPERTY}/PROPERTY_DETAIL`;

export const EXPENSE = `${DEAL}/EXPENSES/EXPENSE`;
export const LIABILITY = `${DEAL}/LIABILITIES/LIABILITY`;
export const LIABILITY_DETAIL = `${LIABILITY}/LIABILITY_DETAIL`;

export const LOAN = `${DEAL}/LOANS/LOAN`;
export const AMORTIZATION_RULE = `${LOAN}/AMORTIZATION/AMORTIZATION_RULE`;
export const LOAN_DETAIL = `${LOAN}/LOAN_DETAIL`;
export const TERMS_OF_LOAN = `${LOAN}/TERMS_OF_LOAN`;
export const UNDERWRITING_VERIFICATION = `${LOAN}/EXTENSION/OTHER/DU:LOAN_EXTENSION/DU:UNDERWRITING_VERIFICATIONS/DU:UNDERWRITING_VERIFICATION`;

export const PARTY = `${DEAL}/PARTIES/PARTY`;
export const INDIVIDUAL_NAME = `${PARTY}/INDIVIDUAL/NAME`;
export const TAXPAYER_IDENTIFIER = `${PARTY}/TAXPAYER_IDENTIFIERS/TAXPAYER_IDENTIFIER`;
export const ROLE = `${PARTY}/ROLES/ROLE`;
export const ROLE_DETAIL = `${ROLE}/ROLE_DETAIL`;
export const BORROWER = `${ROLE}/BORROWER`;
export const BORROWER_DETAIL = `${BORROWER}/BORROWER_DETAIL`;
export const BANKRUPTCY = `${BORROWER}/BANKRUPTCIES/BANKRUPTCY`;
export const DECLARATION = `${BORROWER}/DECLARATION`;
export const DECLARATION_DETAIL = `${DECLARATION}/DECLARATION_DETAIL`;
export const EMPLOYER = `${BORROWER}/EMPLOYERS/EMPLOYER`;
export const CURRENT_INCOME_ITEM = `${BORROWER}/CURRENT_INCOME/CURRENT_INCOME_ITEMS/CURRENT_INCOME_ITEM`;
export const CURRENT_INCOME_ITEM_DETAIL = `${CURRENT_INCOME_ITEM}/CURRENT_INCOME_ITEM_DETAIL`;
export const RESIDENCE = `${BORROWER}/RESIDENCES/RESIDENCE`;
export const RESIDENCE_DETAIL = `${RESIDENCE}/RESIDENCE_DETAIL`;
