#!/usr/bin/env node
/**
 * Embed the two vendored CFPB documents into `@hm/shared`.
 *
 * `data/ffiec-yield-table-fixed.txt` is the CFPB's PUBLISHED fixed-rate average
 * prime offer rate table — one Monday per row, the file their own rate-spread
 * calculator reads — and `data/ffiec-survey-table.csv` is the weekly survey
 * those rates are computed from. Each has a `.meta.json` beside it holding what
 * the server said when it was fetched. All four are written by
 * `npm run apor:vendor` and never by hand. This script turns them into
 * TypeScript constants so that the fixture adapter, the engine's built-in table
 * and the tests all read the same documents — and so a browser bundle can carry
 * them without a filesystem.
 *
 * Nothing here interprets either file. Parsing, and the Appendix J computation
 * that cross-checks the published table against the survey, live in
 * `packages/underwriting/src/apor-yield.ts` and `apor-survey.ts`, in exactly
 * one place, so the table the tests use and the table a deployment fetches are
 * produced by the same code. A generator that also parsed would be a second
 * parser.
 *
 *   node scripts/build-apor.mjs            # regenerate
 *   node scripts/build-apor.mjs --verify   # fail if it would change
 *
 * `npm run apor:verify` is wired into `npm run check` and into CI, the same
 * way the requirement registry, the brand tokens and the DU tables are.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "packages/shared/src/generated/ffiec-survey.ts");

function vendored(base, mustStartWith) {
  const body = readFileSync(resolve(ROOT, `data/${base}`), "utf8");
  const metaPath = resolve(ROOT, `data/${base.replace(/\.[a-z]+$/, "")}.meta.json`);
  const meta = JSON.parse(readFileSync(metaPath, "utf8"));
  for (const key of ["url", "retrievedAt", "lastModified", "etag"]) {
    if (typeof meta[key] !== "string" || meta[key].length === 0) {
      console.error(`✗ ${metaPath} is missing "${key}". Run: npm run apor:vendor`);
      process.exit(1);
    }
  }
  if (!body.startsWith(mustStartWith)) {
    console.error(`✗ data/${base} does not begin with ${JSON.stringify(mustStartWith)}.`);
    process.exit(1);
  }
  return { ...meta, sha256: createHash("sha256").update(body).digest("hex"), body };
}

const yieldTable = vendored("ffiec-yield-table-fixed.txt", "Term of Loan in Years|1|2|");
const survey = vendored("ffiec-survey-table.csv", "Date,");

const banner = `// GENERATED by scripts/build-apor.mjs from data/ffiec-yield-table-fixed.txt,
// data/ffiec-survey-table.csv and their .meta.json files. Do not edit. Run
// \`npm run apor:vendor\` to refresh both from the CFPB and \`npm run apor:build\`
// to re-embed them; \`npm run apor:verify\` fails if this file and the vendored
// documents disagree.`;

const constant = (name, doc, bodyKey, what) => `
/**
 * ${what}
 *
 * \`${bodyKey}\` is the document exactly as the CFPB served it; the other
 * fields are what the server said about it, so that a table read from this
 * constant can name the publication it came from.
 */
export const ${name} = {
  url: ${JSON.stringify(doc.url)},
  retrievedAt: ${JSON.stringify(doc.retrievedAt)},
  lastModified: ${JSON.stringify(doc.lastModified)},
  etag: ${JSON.stringify(doc.etag)},
  sha256: ${JSON.stringify(doc.sha256)},
  ${bodyKey}: ${JSON.stringify(doc.body)},
} as const;
`;

const out = `${banner}
${constant(
  "FFIEC_YIELD_TABLE_FIXED",
  yieldTable,
  "body",
  "The CFPB's published fixed-rate average prime offer rate table, as vendored:\n * one Monday per row, terms of 1 to 50 years, pipe-delimited. The table their\n * own rate-spread calculator reads, and the figure in force for every week it\n * holds.",
)}${constant(
  "FFIEC_SURVEY",
  survey,
  "csv",
  "The CFPB's weekly mortgage-rate survey, as vendored: one row per Thursday,\n * the rates and points the published table is computed from. The cross-check,\n * not the source of truth.",
)}`;

if (process.argv.includes("--verify")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    console.error("✗ packages/shared/src/generated/ffiec-survey.ts is missing. Run: npm run apor:build");
    process.exit(1);
  }
  if (current !== out) {
    console.error(
      "✗ ffiec-survey.ts is out of date with the vendored CFPB documents. Run: npm run apor:build",
    );
    process.exit(1);
  }
  console.log(
    `✓ ffiec-survey.ts matches the vendored documents (table ${yieldTable.sha256.slice(0, 12)}…, survey ${survey.sha256.slice(0, 12)}…)`,
  );
} else {
  writeFileSync(OUT, out);
  console.log(`wrote ${OUT} (table ${yieldTable.body.length} bytes, survey ${survey.body.length} bytes)`);
}
